### ISSUE TITLE
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by mialrr** [yangxue0827/R2CNN_FPN_Tensorflow#13]
if d.decorator_argspec is not None), _inspect.getargspec(target))
/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
Traceback (most recent call last):
  File "/home/louj/pywork/R2CNN_FPN/tools/inference1.py", line 17, in <module>
    from libs.fast_rcnn import build_fast_rcnn1
  File "/home/louj/pywork/R2CNN_FPN/libs/fast_rcnn/build_fast_rcnn1.py", line 14, in <module>
    from libs.box_utils import nms_rotate
  File "/home/louj/pywork/R2CNN_FPN/libs/box_utils/nms_rotate.py", line 12, in <module>
    from libs.box_utils.rotate_polygon_nms import rotate_gpu_nms
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory

**Comment by yangxue0827** [comment]
Environment Configuration: python2 + tensorflow1.2 + cv2 + cuda8.0

**Comment by Marcus208** [comment]
lucky u can use this to make a soft link:   
cd /usr/local/cuda/lib64
sudo ln -s libcudart.so.9.2.148 libcudart.so.8.0

9.2.148 is my cuda version

**Comment by Andyflying** [comment]
can‘t use CUDA9.0？

**Comment by hilnkm** [comment]
I have solved this problem like this:

#############################
cd $PATH_ROOT/libs/box_utils/
python3 setup.py build_ext --inplace
#############################
